language: python
python: '3.6'
install:
- pip install -r requirements.txt
script:
- python -m compileall ./bot.py
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: nQWtN+TGp4XVZi7xd9JW2vMl0Nu2kVMQOTtrJFq4CN6LXVsvM2pBZ+/PM9g8HZKWrntrecXNhv65Wfg2yitpyjyDEupVlFoURzwvNntla2pLdB1ohuqH5EX2He240VKrjfHZvq7Fw8Pf5vk9MLMUfdn3lPI+Bw3eBj9RKGbFAkm8D722JfDXMGqKKZ3DSE3icvm+1LaY5Mwu/fKYiB8eiYO4lc7S+mHbanqVBgm++UztCOYySjZmajtXiji0V6oRpsio2w1DOkdostzeBZmuc2oGdxWr0/U5CLpoPV4GNhhf042/ud+X+8oq0UVnewTR+TL459gWwTpndc7aZjaFiRwsypX6gQY24gV/OLvQ3BvIWLGYVdSXWz+2cty/qjzoCnEKCScAPC5ezHGqx0iUvFL4z1dyUc41Tt+YhXZYjoEPkonCNCYcpMG71PPa9GvD0cLrqdTe8FoshDiyvcS6UgaSlMrfQGkpx+OCFTISodlz+eI16GhxVIwnHpTEX4VcbQfBoZqQ5waUwWK2i9U0J51ZZZ7P4VbgwZ87qW1ASG0eb7CyRFxSXWuAiM7L9z9HTqwgP+99zbFcUObOlE3p/ImgPZC1g9vDBK9IpQKgOQWMMeGQKmQ1XyXp1o+aKkIVzsU2A+CdIE3EhUvjAq3Y4+uTI9copbnVPwMOKpkE3iI=
  app: leripinho-bot
  on:
    repo: felipesena/leripinho-bot
notifications:
  email: true
